from .WindowFunctions import ApplyWindowFunction,WindowScaleFactor
from .PlotPolarization import PlotPolarization
from .Polarization2D import Polarization2D
from .UTPlotLabel import UTPlotLabel
from .PolyDetrend import PolyDetrend
from .RemoveStep import RemoveStep
from .DetectGaps import DetectGaps 
from .GetWindows import GetFFTWindows,GetLSWindows
from .mode import mode
from .kVector import kVector
